apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deploy
  labels:
    app: flask-app-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      project: flask-app
  template:
    metadata:
      labels:
        project: flask-app
    spec:
      containers:
        - name: flask-app
          image: ilyazawyalowww/reg_service:v22
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  labels:
    owner: IlyaZawyalow
spec:
  selector:
    project: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30000
  type: NodePort